apiVersion: apps/v1
kind: Deployment
metadata:
  name: shifu-demo-deployment
  namespace: shifu-demo
  labels:
    app: shifu
spec:
  selector:
    matchLabels:
      app: shifu
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: shifu
    spec:
      containers:
        - image: testharbor.com/shifu-demo/shifu-demo:{VERSION}
          name: shifu-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              protocol: TCP